### ISSUE TITLE
Create branches to which to push unfinished BPP features

### ISSUE THREAD

**Issue by davidskalinder** [MPEDS/mpeds-coder#71]
As discussed in today's meeting, there are five or six branches for unfinished features in the BPP repo that I won't get to before I leave, so the best thing will be to create some new branches in this repo and PR the unfinished ones to those new branches; after that @alexhanna can manage them as she wants.

First step: see if I can create them thar new branches.

**Comment by davidskalinder** [comment]
Okay it doesn't look like I have write permission for this repo ATM.  @alexhanna you could grant it for me, but at this stage it's probably easier for you to just create the branches?  Here's the list:

```
chunk_event_export_test
create_export_page
modularize_event_export
py3_upstream
remove_coder_table_button
```

There's also `assignment_comments` and `modularize_event_export_minimal` that have been PR'd already, and `create_modules_dir` which is part of 
`modularize_event_export_minimal`; so I guess @alexhanna it's up to you whether to create branches for those or simply to accept the PRs and I can delete the branches.

Let me know when these are set up and I'll PR my branches to the corresponding ones here.

**Comment by alexhanna** [comment]
Oh, hrm, why can't you create the branches? I can add you as a collab to the repo. I'd rather you do it.

**Comment by davidskalinder** [comment]
Yeah that'd be fine too.  Here's what I got when I tried to push:

```
git push --set-upstream origin py3_upstream
remote: Permission to MPEDS/mpeds-coder.git denied to davidskalinder.
fatal: unable to access 'https://github.com/MPEDS/mpeds-coder.git/': The requested URL returned error: 403
```

Which I think means I don't have push permission yet?

**Comment by alexhanna** [comment]
You had an invite outstanding. I think I resent it tho?

**Comment by davidskalinder** [comment]
Hmm I got one to the MPEDS org, but I don't think it gave me write permissions on this repo?  Let me know if I should do anything to check this though...

**Comment by alexhanna** [comment]
Says you should be able to push in permissions?

**Comment by davidskalinder** [comment]
Uh yep works now.  Who knows/cares whether it was the permissions or a connection issue or something.  Anyway, looking good, will start a-pushin'.

**Comment by davidskalinder** [comment]
Hey @alexhanna do you want me to prefix the branch names with `bpp_` so you'll be able to ID them later?

**Comment by alexhanna** [comment]
Sure, that's fine.

**Comment by davidskalinder** [comment]
You gwot it

**Comment by davidskalinder** [comment]
Okay all the branches should be pushed.  PRs imminent.

**Comment by davidskalinder** [comment]
Okay these should all be PR'd now, so I think @alexhanna it's all in your hands.  Further doubts probably belong in the PR threads, so I'll close this one.

**Comment by alexhanna** [comment]
There were some weird merges in there (e.g. not sure why there was a clash between the admin page which shows the publication reports and why that's in the master) but these are all in branches anyhow, so I wasn't too concerned with it.

**Comment by davidskalinder** [comment]
Yeah I suspect that's because the export page link would go in the same place that some of those publication reports you put in? But yes, everything should be safely tucked away in branches and easy to review more carefully if and when it gets merged in I think.

--
